### ISSUE TITLE
Issue-Add token contract and the test

### ISSUE THREAD

**Issue by satomichru** [satomichru/tol-contract#12]
Automated Review Comments
Issues in contracts/Common/Context.sol:
  - (9, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
Issues in contracts/Common/Ownable.sol:
  - (12, 'Line exceeds 80 characters')
Issues in contracts/ERC20/ERC20.sol:
  - (19, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (73, 'Line exceeds 80 characters')
  - (103, 'Line exceeds 80 characters')
  - (109, 'Line exceeds 80 characters')
  - (111, 'Line exceeds 80 characters')
  - (163, 'Line exceeds 80 characters')
  - (203, 'Line exceeds 80 characters')
  - (227, 'Line exceeds 80 characters')
  - (258, 'Line exceeds 80 characters')
  - (275, 'Line exceeds 80 characters')
  - (320, 'Line exceeds 80 characters')
  - (365, 'Line exceeds 80 characters')
  - (419, 'Line exceeds 80 characters')
Issues in contracts/ERC20/IERC20.sol:
  - (30, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (66, 'Line exceeds 80 characters')
  - (80, 'Line exceeds 80 characters')
Issues in contracts/Math/Math.sol:
  - (32, 'Line exceeds 80 characters')
Issues in contracts/Math/SafeMath.sol:
  - (49, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')
  - (76, 'Line exceeds 80 characters')
  - (76, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (105, 'Line exceeds 80 characters')
  - (117, 'Line exceeds 80 characters')
  - (121, 'Line exceeds 80 characters')
  - (127, 'Line exceeds 80 characters')
  - (142, 'Line exceeds 80 characters')
  - (154, 'Line exceeds 80 characters')
Issues in contracts/Utils/Address.sol:
  - (46, 'Line exceeds 80 characters')
  - (51, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (70, 'Line exceeds 80 characters')
  - (79, 'Line exceeds 80 characters')
  - (84, 'Line exceeds 80 characters')
  - (89, 'Line exceeds 80 characters')
  - (104, 'Line exceeds 80 characters')
  - (105, 'Line exceeds 80 characters')
  - (109, 'Line exceeds 80 characters')
  - (114, 'Line exceeds 80 characters')
  - (115, 'Line exceeds 80 characters')
  - (119, 'Line exceeds 80 characters')
  - (129, 'Line exceeds 80 characters')
  - (130, 'Line exceeds 80 characters')
  - (134, 'Line exceeds 80 characters')
  - (139, 'Line exceeds 80 characters')
  - (153, 'Line exceeds 80 characters')
  - (154, 'Line exceeds 80 characters')
  - (158, 'Line exceeds 80 characters')
  - (163, 'Line exceeds 80 characters')
  - (171, 'Line exceeds 80 characters')
  - (177, 'Line exceeds 80 characters')
Issues in test/TOLToken.js:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (71, 'Line exceeds 80 characters')
  - (77, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (94, 'Line exceeds 80 characters')
  - (97, 'Line exceeds 80 characters')
  - (97, 'Hardcoded string found')

**Comment by lind0118** [comment]
I got it.
