### ISSUE TITLE
Issue-Add launchpad contract

### ISSUE THREAD

**Issue by satomichru** [satomichru/tol-contract#14]
Automated Review Comments
Issues in contracts/ERC20/ERC20.sol:
  - (12, 'Line exceeds 80 characters')
Issues in contracts/ERC20/IERC20.sol:
  - (5, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
Issues in contracts/Launchpad/Board.sol:
  - (49, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (109, 'Line exceeds 80 characters')
  - (122, 'Line exceeds 80 characters')
  - (157, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
  - (164, 'Line exceeds 80 characters')
  - (165, 'Hardcoded string found')
  - (175, 'Line exceeds 80 characters')
  - (181, 'Hardcoded string found')
  - (191, 'Line exceeds 80 characters')
  - (195, 'Hardcoded string found')
  - (197, 'Hardcoded string found')
  - (205, 'Line exceeds 80 characters')
  - (209, 'Hardcoded string found')
  - (211, 'Hardcoded string found')
  - (222, 'Line exceeds 80 characters')
  - (229, 'Hardcoded string found')
  - (243, 'Hardcoded string found')
  - (244, 'Line exceeds 80 characters')
  - (244, 'Hardcoded string found')
  - (265, 'Line exceeds 80 characters')
  - (271, 'Line exceeds 80 characters')
  - (271, 'Hardcoded string found')
  - (275, 'Hardcoded string found')
  - (294, 'Hardcoded string found')
Issues in contracts/Launchpad/BoardFactory.sol:
  - (27, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (51, 'Line exceeds 80 characters')
  - (66, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
Issues in contracts/Launchpad/IOcean.sol:
  - (8, 'Line exceeds 80 characters')
Issues in contracts/Launchpad/Ocean.sol:
  - (48, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (132, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (151, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (154, 'Hardcoded string found')
  - (174, 'Line exceeds 80 characters')
  - (185, 'Hardcoded string found')
  - (198, 'Hardcoded string found')
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
Issues in pnpm-lock.yaml:
  - (13, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
Issues in test/BoardFactory.js:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (93, 'Line exceeds 80 characters')
  - (97, 'Hardcoded string found')
  - (111, 'Hardcoded string found')
  - (125, 'Line exceeds 80 characters')
  - (133, 'Hardcoded string found')
  - (144, 'Line exceeds 80 characters')
  - (147, 'Line exceeds 80 characters')
  - (153, 'Line exceeds 80 characters')
  - (153, 'Hardcoded string found')
  - (163, 'Line exceeds 80 characters')
Issues in test/Ocean.js:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')
  - (56, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (72, 'Line exceeds 80 characters')
  - (72, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (78, 'Line exceeds 80 characters')
  - (78, 'Hardcoded string found')

**Comment by lind0118** [comment]
I got it.
