### ISSUE TITLE
Issue-Add simple token factory

### ISSUE THREAD

**Issue by satomichru** [satomichru/tol-contract#16]
Automated Review Comments
Issues in test/TokenFactory.js:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')

**Comment by lind0118** [comment]
I got it.
