### ISSUE TITLE
Issue-Add governance contracts

### ISSUE THREAD

**Issue by satomichru** [satomichru/tol-contract#18]
Automated Review Comments
Issues in contracts/Governance/AccessControl.sol:
  - (34, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')
  - (66, 'Line exceeds 80 characters')
  - (74, 'Line exceeds 80 characters')
  - (83, 'Line exceeds 80 characters')
  - (88, 'Line exceeds 80 characters')
  - (104, 'Line exceeds 80 characters')
  - (109, 'Line exceeds 80 characters')
  - (112, 'Line exceeds 80 characters')
  - (137, 'Line exceeds 80 characters')
  - (152, 'Line exceeds 80 characters')
  - (160, 'Line exceeds 80 characters')
  - (172, 'Line exceeds 80 characters')
  - (189, 'Line exceeds 80 characters')
Issues in contracts/Governance/Governance.sol:
  - (9, 'Line exceeds 80 characters')
  - (12, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (65, 'Line exceeds 80 characters')
  - (68, 'Line exceeds 80 characters')
  - (124, 'Line exceeds 80 characters')
  - (127, 'Line exceeds 80 characters')
  - (130, 'Line exceeds 80 characters')
  - (138, 'Line exceeds 80 characters')
  - (141, 'Line exceeds 80 characters')
  - (150, 'Line exceeds 80 characters')
  - (151, 'Line exceeds 80 characters')
  - (152, 'Line exceeds 80 characters')
  - (153, 'Line exceeds 80 characters')
  - (154, 'Line exceeds 80 characters')
  - (159, 'Line exceeds 80 characters')
  - (160, 'Line exceeds 80 characters')
  - (188, 'Line exceeds 80 characters')
  - (193, 'Line exceeds 80 characters')
  - (197, 'Line exceeds 80 characters')
  - (203, 'Line exceeds 80 characters')
  - (204, 'Line exceeds 80 characters')
  - (209, 'Line exceeds 80 characters')
  - (213, 'Line exceeds 80 characters')
  - (220, 'Line exceeds 80 characters')
  - (223, 'Line exceeds 80 characters')
  - (227, 'Line exceeds 80 characters')
  - (233, 'Line exceeds 80 characters')
  - (238, 'Line exceeds 80 characters')
  - (243, 'Line exceeds 80 characters')
  - (251, 'Line exceeds 80 characters')
  - (257, 'Line exceeds 80 characters')
  - (268, 'Line exceeds 80 characters')
  - (269, 'Line exceeds 80 characters')
  - (270, 'Line exceeds 80 characters')
  - (271, 'Line exceeds 80 characters')
  - (273, 'Line exceeds 80 characters')
  - (278, 'Line exceeds 80 characters')
  - (281, 'Line exceeds 80 characters')
  - (298, 'Line exceeds 80 characters')
  - (303, 'Line exceeds 80 characters')
  - (308, 'Line exceeds 80 characters')
  - (313, 'Line exceeds 80 characters')
  - (317, 'Line exceeds 80 characters')
  - (318, 'Line exceeds 80 characters')
  - (319, 'Line exceeds 80 characters')
  - (322, 'Line exceeds 80 characters')
  - (323, 'Line exceeds 80 characters')
  - (324, 'Line exceeds 80 characters')
  - (329, 'Hardcoded string found')
  - (334, 'Hardcoded string found')
  - (350, 'Line exceeds 80 characters')
  - (351, 'Line exceeds 80 characters')
  - (352, 'Line exceeds 80 characters')
Issues in contracts/Governance/SigRelayer2.sol:
  - (10, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (46, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (68, 'Line exceeds 80 characters')
  - (69, 'Line exceeds 80 characters')
  - (70, 'Line exceeds 80 characters')
  - (71, 'Line exceeds 80 characters')
  - (73, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (78, 'Line exceeds 80 characters')
  - (79, 'Line exceeds 80 characters')
  - (80, 'Line exceeds 80 characters')
  - (81, 'Line exceeds 80 characters')
  - (83, 'Hardcoded string found')
Issues in contracts/Governance/Timelock.sol:
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (62, 'Line exceeds 80 characters')
  - (63, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (66, 'Line exceeds 80 characters')
  - (73, 'Line exceeds 80 characters')
  - (74, 'Line exceeds 80 characters')
  - (76, 'Line exceeds 80 characters')
  - (82, 'Line exceeds 80 characters')
  - (83, 'Line exceeds 80 characters')
  - (85, 'Line exceeds 80 characters')
  - (86, 'Line exceeds 80 characters')
  - (87, 'Line exceeds 80 characters')
  - (88, 'Line exceeds 80 characters')
  - (97, 'Line exceeds 80 characters')
  - (101, 'Line exceeds 80 characters')
  - (102, 'Line exceeds 80 characters')

**Comment by lind0118** [comment]
I got it.
