### ISSUE TITLE
Issue-Add faucet contract

### ISSUE THREAD

**Issue by satomichru** [satomichru/tol-contract#20]
Automated Review Comments
Issues in contracts/Faucet.sol:
  - (55, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
Issues in test/Faucet.js:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (39, 'Line exceeds 80 characters')
  - (43, 'Hardcoded string found')
  - (50, 'Line exceeds 80 characters')
  - (50, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (58, 'Line exceeds 80 characters')
  - (63, 'Line exceeds 80 characters')
  - (67, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (92, 'Hardcoded string found')

**Comment by lind0118** [comment]
I got it.
