### ISSUE TITLE
Issue-Add license and update README

### ISSUE THREAD

**Issue by satomichru** [satomichru/tol-contract#4]
Automated Review Comments
Issues in LICENSE:
  - (8, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (267, 'Hardcoded string found')
  - (370, 'Hardcoded string found')
  - (373, 'Hardcoded string found')
  - (438, 'Hardcoded string found')
  - (439, 'Hardcoded string found')
  - (444, 'Hardcoded string found')
  - (637, 'Hardcoded string found')
  - (665, 'Hardcoded string found')
  - (700, 'Hardcoded string found')
Issues in README.md:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (70, 'Hardcoded string found')
  - (74, 'Line exceeds 80 characters')
  - (78, 'Line exceeds 80 characters')
  - (83, 'Line exceeds 80 characters')

**Comment by lind0118** [comment]
I got it.
